export const REQUEST_SWITCH_APP = 'REQUEST_SWITCH_APP';
export const REQUEST_SWITCH_APP_SUCCESS = 'REQUEST_SWITCH_APP_SUCCESS';
export const REQUEST_APP_MESSAGES = 'REQUEST_APP_MESSAGES';
export const REQUEST_APP_MESSAGES_SUCCESS = 'REQUEST_APP_MESSAGES_SUCCESS';
export const REQUEST_APP_MESSAGES_FAILURE = 'REQUEST_APP_MESSAGES_FAILURE';
